import {StyleSheet, Dimensions, StatusBar} from 'react-native';
import {theme} from '../styles/theme';

const deviceHeight = Dimensions.get('window').height;
const deviceWidth = Dimensions.get('window').width;

export const modalstyles = StyleSheet.create({
  container: {
    flex: 1,
    // marginTop: '25%',
    // borderTopLeftRadius: 30,
    // borderTopRightRadius: 30,
    // backgroundColor: theme.COLORS.BACKGROUND,
    // paddingBottom: '5%',
    backgroundColor: 'beige',
    // overflow: 'hidden',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 292,
  },
  modalText: {
    marginBottom: '150%',
    bottom: 70,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 24,
    //fontFamily: 'AntDesign',
    color: 'green',
    textTransform: 'uppercase',
    // fontWeight: 'bold',
  },
  modal: {
    // width: '100%',
    // height: '100%',
    // marginTop: '50%',
    height: deviceHeight,
    width: deviceWidth,
    marginTop: '90%',
    position: 'absolute',
    top: 60,
    left: 0,
    backgroundColor: 'red',
    // colors={['#191919', '#f9d29d']}
    justifyContent: 'center',
    borderRadius: 20,
    // flexDirection: 'row',
  },
  instagramButton: {
    // paddingHorizontal: 40,
    // paddingVertical: 10,
    // width: 150,
    width: Dimensions.get('screen').width * 0.44,
    height: 52,
    borderRadius: 30,
    margin: 20,
    alignSelf: 'center',
  },
  signUpButton: {
    margin: 1,
    // width: 200,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: 'white',
    width: '40%',
    // height: 42,
  },
  stakeUnstakeButtons: {
    // marginTop: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stakeUnstakeButtonStyle: {
    borderRadius: 30,
    width: Dimensions.get('screen').width * 0.44,
    backgroundColor: 'gold',
    opacity: 0.1,
  },
  stakeButtonText: {
    fontSize: 18,
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
    marginTop: 10,
    // justifyContent: 'center',
    // alignItems: 'center',
    textAlign: 'center',
    // textAlignVertical: 'center',
  },
  unstakeButtonText: {
    fontSize: 18,
    //fontFamily: 'AntDesign',
    textTransform: 'uppercase',
    textAlignVertical: 'center',
    color: theme.COLORS.LIGHT_RED,
  },
  cardCover: {
    height: '50%',
    width: '100%',
  },
  countdownContainer: {
    left: 0,
    right: 0,
    top: '32%',
    borderRadius: 60,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    paddingHorizontal: 28,
    marginHorizontal: '10%',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_1,
  },
  countdownItem: {
    alignItems: 'center',
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  countdownLabel: {
    fontSize: 12,
    lineHeight: 14,
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  countdownvalue: {
    fontSize: 32,
    lineHeight: 40,
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  companyInfoContainer: {
    marginTop: '25%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: theme.APP_COLOR_1,
  },
  companyInfoContentContainer: {
    paddingBottom: '10%',
  },
  info: {
    paddingVertical: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopColor: theme.COLORS.DARK_PURPLE,
    borderWidth: 5,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    // backgroundColor: 'beige',
    // backgroundColor: theme.COLORS.BACKGROUND,
    // paddingBottom: '5%',
  },
  infoImage: {
    width: 100,
    height: 100,
    marginRight: 22,
  },
  companyTitle: {
    fontSize: 16,
    lineHeight: 24,
    //fontFamily: 'AntDesign',
    color: theme.COLORS.DARK_PURPLE,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  tags: {
    marginTop: 9,
    flexDirection: 'row',
  },
  tag: {
    marginRight: 8,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10.5,
    backgroundColor: 'green',
  },
  tagText: {
    fontSize: 18,
    lineHeight: 18,
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  mainDivider: {
    // height: 0.2,
    backgroundColor: theme.APP_COLOR_2,
  },
  rewardContainer: {
    paddingVertical: 20,
    paddingHorizontal: 40,
    justifyContent: 'center',
  },
  rewardTitle: {
    fontSize: 16,
    lineHeight: 14,
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  rewardItem: {
    flexWrap: 'wrap',
    marginTop: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exp: {
    borderRadius: 30,
    paddingVertical: 1,
    paddingHorizontal: 9,
    backgroundColor: theme.APP_COLOR_2,
  },
  expText: {
    fontSize: 16,
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  rewardItemTitle: {
    flexDirection: 'row',
    flex: 0.3,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  x: {
    fontSize: 10,
    lineHeight: 9.2,
    marginHorizontal: 10,
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  rewardSign: {
    width: 20,
    height: 20,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.COLORS.YELLOW,
  },
  rewardSignText: {
    fontSize: 16,
    //fontFamily: 'AntDesign',
    color: theme.APP_COLOR_1,
    textTransform: 'uppercase',
  },
  button: {
    marginTop: 30,
    marginHorizontal: '10%',
  },
  buttonIcon: {
    marginRight: 10,
  },
  buttonOuter: {
    width: '100%',
    borderRadius: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },
  radius30: {
    borderRadius: 30,
  },
  gradientButtonInner: {
    width: '100%',
    borderRadius: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '5%',
    paddingHorizontal: '1%',
    justifyContent: 'center',
  },
  leftButton: {
    width: 40,
    height: 40,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
  },
  buttonText: {
    fontSize: 16,
    textAlign: 'center',
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  tcText: {
    padding: 38,
    fontSize: 16,
    lineHeight: 29,
    textAlign: 'center',
    //fontFamily: 'AntDesign',
    color: theme.COLORS.WHITE,
    textTransform: 'uppercase',
  },
  actionContainer: {
    paddingHorizontal: 40,
  },
  radioButtonContainer: {
    paddingTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonText: {
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'left',
    paddingHorizontal: 16,
    //fontFamily: 'AntDesign',
    textTransform: 'uppercase',
    color: theme.COLORS.SILVER,
  },
  radioButtonTextLink: {
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'left',
    paddingHorizontal: 16,
    //fontFamily: 'AntDesign',
    textTransform: 'uppercase',
    color: theme.COLORS.DARK_BLUE,
    textDecorationLine: 'underline',
  },

  //RadioButton Styling
  radioButton: {
    width: 32,
    height: 32,
    borderWidth: 2,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.APP_COLOR_2,
    borderColor: theme.COLORS.LIGHT_GREY,
  },
  radioButtonDot: {
    width: 16,
    height: 16,
    borderRadius: 25,
    backgroundColor: theme.APP_COLOR_2,
  },
});
